server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      authorized-endpoints:
        - path: /restaurants/**
          roles: ["ADMIN", "USER"]
        - /orders/**
        - /users/**
        -
      routes:
        - id: restaurant-service
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
    discovery:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
  profiles:
    active: default
jwt:
  secret: 3e7cbe8aebe67cf7c758b216ea0dd42edc43c1befc1d36f72cd6bc5f29d8567c8bf85972b636c3275b27e80940eb9d67cb61ea00bd8f07a62f62b7c0aeef4ca5

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true


